[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.18.1"
interprocess = "2.2.1"
raw-window-handle = "0.5"
tao = { version = "0.30.3", features = ["rwh_05"] }
wry = "0.45.0"
x11rb = "0.13.1"
